name: i2k
channels:
- conda-forge
dependencies:
- python=3.8
- pip
- numpy
- scipy
- scikit-image
- scikit-learn
- dask
- bokeh
- ipython
- matplotlib
- jupyter
- notebook
- napari
- pandas
- seaborn
- dask-image
- magicgui
- pip:
    - jupyter-book
